/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-107817-g48be6616d0-20220818"
#endif /* AVUTIL_FFVERSION_H */
